### ISSUE TITLE
[id3] tags incorrect

### ISSUE THREAD

**Issue by ildar** [moritz-weber/mucke#82] opened 2023-05-11 21:31 UTC
**Describe the bug**
some mp3 files imported with partially incorrect song infos. The mp3s having cyrillic tags

**To Reproduce**
1. [Get these tracks](https://open.audio/library/albums/19364/)
2. put them somewhere in your android phone or emulator
3. Update Library
4. See the songs having incorrect Artist name or Album name but other tags are ok

**Smartphone (please complete the following information):**
 - Device: AGM H3
 - OS: Android 13 / LOS GSI
 - Version Mucke 1.3.0

**Comment by moritz-weber** [comment] 2023-05-12 13:52
I can confirm this behavior. Furthermore, the problem also arises in [Simple Music Player](https://f-droid.org/en/packages/com.simplemobiletools.musicplayer/).

Unfortunately, I use a third-party plugin to parse the music files: https://github.com/LucJosin/on_audio_query

With the original files you provided, I only get the file names as song titles, for example. When I run the files through Musicbrainz Picard to complete the tags, I get '??? ?? ???' with the correct number of characters. The plugin seems to have a problem with Cyrillic letters. Since I can't fix this in my app, I'd suggest opening an issue in the plugin repo.

**Comment by moritz-weber** [comment] 2023-05-12 13:54
Added a wontfix tag, since I simply don't have the time to contribute to the plugin. I'll leave the issue open, though, in case someone wants to pick it up.

**Comment by moritz-weber** [comment] 2023-05-13 10:01
One thing that is weird, these tags look ok for the FLAC files from #70 ...

**Comment by ildar** [comment] 2023-05-17 00:12
The root cause is that the file has id3 v 2.4. Opened the issue in
upstream: https://github.com/LucJosin/on_audio_query/issues/121

**Closed** 2023-06-19 18:13 UTC
Labels: bug, wontfix
