### ISSUE TITLE
Cover image not displayed in some cases

### ISSUE THREAD

**Issue by JustToby22** [moritz-weber/mucke#60] opened 2023-02-18 12:41 UTC
I have noticed that when playing some of my audio files the album cover isn't displayed. After some fiddling I'm pretty sure this affects files where the covers don't have a 1:1 aspect ratio. Tested with FLAC and MP3.

Steps to reproduce: Ripped CD and added image (500x488p) on Linux using EasyTag (EasyTag categorises the image as "Cover (front)"), send over to smartphone, rescan library, open song. Album art not displayed.

Fix: Resized image to 488x488 pixels, added using EasyTag, sent to smartphone, rescanned library. Cover art displays correctly.

I'm running Mucke v1.1.0 on a Fairphone 4 eith Android 12 stock.

**Comment by moritz-weber** [comment] 2023-02-18 21:34
Thanks for your report. I have a few albums in my library that have different aspect ratios and show up just fine (just cropped to 1:1). Thus, I'm pretty confident that the aspect ratio is not an issue.

BTW I'm using the same hardware and software, so you should get the best possible support ;)

**Comment by JustToby22** [comment] 2023-02-18 21:45
A fellow Fairphone user, Nice!
Interesting it's not the aspect ratio that's the problem, though I seem to just not have tested it enough. If it helps, I'll send the two files from my example. Maybe that can help diagnose the issue.
Original:
![Guns N' Roses - Use Your Illusion II - album_art](https://user-images.githubusercontent.com/85606405/219900735-36b300c0-0458-433d-8ebc-cb8870f56677.jpg)
Resized:
![Guns N' Roses - Use Your Illusion II - album_art_1x1](https://user-images.githubusercontent.com/85606405/219900753-c78c6b09-62a8-48c4-ab05-1e3928b4cc9a.jpg)

Also, here is another album cover that doesn't show up in the app. I haven't tried to resize this one yet for lack of time.
![Die Ärzte - Ein Song namens Schunder - album_cover](https://user-images.githubusercontent.com/85606405/219900762-0251f2ba-d6a3-4ebf-a494-64fafd7d1c8a.jpg)

**Comment by moritz-weber** [comment] 2023-02-19 10:02
Just tried both original files without any problems. I just set them as cover images for some random songs with MusicBrainz Picard:

![Screenshot_20230219-105805](https://user-images.githubusercontent.com/17176771/219941215-0c854ab4-5e6a-4ec3-8b4a-9acc6ae04986.png)

**Comment by JustToby22** [comment] 2023-02-20 12:15
Very interesting. I've been testing a bit with using different encodings for the metadata and switching between ID3v2.3 and v2.4 but no luck so far. Would it be possible for me to send you one of the audio files, maybe? I'm not sure what the guidelines say about sending media files like music.

**Comment by moritz-weber** [comment] 2023-03-01 19:20
Even using the same MP3 files, the problem could not be recreated. It seems to be a problem with the metadata plugin, but it is unclear, what causes this issue.

**Comment by moritz-weber** [comment] 2023-06-17 10:27
@JustToby22 there is currently a new implementation of the metadata reader in testing. Could you try out the new build and let me know if this fixes your issue?

https://drive.google.com/file/d/1V1NI5stTFjQdtnyaKv4tX9umyiTCETZc/view?usp=sharing

**Comment by JustToby22** [comment] 2023-06-19 06:15
This fixes the issue, indeed. Funnily enough, it breaks some other covers at the same time. So far I've only noticed the covers of the Half Life games' soundtracks missing, though.

**Comment by Knusper** [comment] 2023-07-13 19:25
OK... I just updated and now I also experiences missing covers

**Comment by moritz-weber** [comment] 2023-07-14 08:32
Yeah, that makes sense. With the new metadata reader, we just read the music files. I wasn't aware that the previous scanner also scanned for image files in the folders. The problem shouldn't be too hard to fix, but I can't make any promises about when I have time to work on this. Sorry for the inconvenience.

**Comment by Knusper** [comment] 2023-07-14 14:40
Ah .. no worries... I revert to the previous version for full cover glory in the meantime ... thanks for this app!

**Comment by moritz-weber** [comment] 2023-07-15 19:54
I wrote a quick fix for this. Would you mind trying this build ([Google Drive](https://drive.google.com/file/d/1V1NI5stTFjQdtnyaKv4tX9umyiTCETZc/view))?

This just grabs the first jpg or png file it finds in the album folder and uses it as the cover (if there is no image in the meta data).

**Comment by jdg2011** [comment] 2023-07-29 18:03
I've tested the build linked above, and it solved my original problem of new album art not being imported in version 1.4.

However, in my music collection I have a mix of album art that I named "cover.jpg" and art that was auto-downloaded with another tool where the art has names like "AlbumArt_{B5020207-474E-4720-A6EC-E32AD8402400}_Large.jpg". In other versions of mucke, including 1.4, those images with the longer names got imported, but not in this build.

**Comment by FriederHannenheim** [comment] 2023-07-29 18:06
The root cause of this is probably that images specified as paths in id3 tags are not automatically parsed by the new system. I will modify metadata_god to do that soon. This should be fixed after

**Comment by moritz-weber** [comment] 2023-07-29 20:39
In the current fix, mucke just scans the folder for images (if there is no cover in the tags) and uses the first one it finds as the album cover. Is the problem that you would prefer the auto-downloaded images over the cover.jpg files?

I can't really imagine that 1.4 imported those images, since I just added the following lines to the scanning process:
```dart
if (albumArt == null) {
  // get directory of song and look for image files
  final images = await songFile.parent
      .list(recursive: false, followLinks: false)
      .where((item) =>
          FileSystemEntity.isFileSync(item.path) &&
          IMAGE_EXTENSIONS.contains(p.extension(item.path).toLowerCase().substring(1)))
      .asyncMap((item) => File(item.path))
      .toList();
  if (images.isNotEmpty) albumArt = images.first.readAsBytesSync();
}
```

**Comment by moritz-weber** [comment] 2023-09-10 00:05
@Valotio @chris-blues, would you be so kind to test the [current build for this branch](https://github.com/moritz-weber/mucke/actions/runs/6133763678)?
I'm asking you because you now have quite some experience with testing builds, and you have some extensive libraries that are just good test scenarios :smile: 

This new build just looks for image files in the song folder, if the song file itself does not contain a cover image.

@jdg2011 could you also test this and clarify what the problem with the auto-downloaded images is exactly?

**Comment by chris-blues** [comment] 2023-09-10 06:31
Impressive! This scan took about 4 minutes. All seems well! Sorry, I couldn't find any logs though...

**Comment by Valotio** [comment] 2023-09-10 06:57
For me it worked perfectly. The scanning of 4669 Songs took about 20 Seconds. Logfile is as always placed in /storage/emulated/0/Android/data/rocks.mucke.dev
Good Job, bye

**Closed** 2023-09-26 00:15 UTC
Labels: bug, missing info
